twitter: 
github: "https://github.com/TimSamuelsen"
linkedin: "https://www.linkedin.com/timsamuelsen"
youtube: ""
dribbble: ""
instagram: ""
facebook: ""
medium: ""
patreon: ""
paypal: ""
unsplash: ""
